Roboy 20 questions game
Roboy/DialogSystem pull request #41
Opened 2018-06-05 10:05 UTC by ninalovegood

20 Questions (Akinator API) and Snapchat game are both working.

2018-06-11 00:25 UTC, Waguramu commented
Why do you PR straight into the master branch? ◟(◔ั₀◔ั )◞

2018-06-13 09:49 UTC, missxa commented
@ninalovegood base branch - devel

2018-06-13 13:19 UTC, missxa requested changes
- all possible answers should go to  src/main/java/roboy/talk/PhraseCollection.java

- use logger
- handle exceptions inside functions
- + refer to comments

2018-06-13 13:19 UTC, missxa commented on config.properties
> +# PERSONALITY_FILE: "resources/personalityFiles/ExpoPersonality.json"
duplicates the line above

2018-06-13 13:19 UTC, missxa commented on resources/personalityFiles/GamePersonality.json
> +      }
we have agreed to have a path to possible filters here as a parameter. why did you change it?

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/eventStates/UzupisState.java
> +        String answer = input.getAnswer();
ignoring this, cause this changes are not yours and are already on devel. please create PRs to devel, not master

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/ChooseGameState.java
> +        return Output.say("What game do you want to play?");
add more options. create a  random list in Verbalizes that contains possible ways to ask this question

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/ChooseGameState.java
> +        return Output.say("Let's play " + getGame(input));
same as above -> goes to Verbalize + more variability

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingSnapchatState.java
> +        return Output.say("What filter do you want? " + possibleFilters);
+ more options

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingSnapchatState.java
> +            filterApplied = rmn.ApplyFilter(desiredFilter);
refactor previous 2 lines to 
filterApplied = getRosMainNode().ApplyFilter(desiredFilter);

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingSnapchatState.java
> +            token = " " + token + " ";
why do you append whitespaces here?

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingSnapchatState.java
> +            System.out.println(filter);
use LOGGER instead of Sytem.out (everywhere, not just here) - look at other states for implementation.

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingSnapchatState.java
> +        //if(input.getSentenceType().compareTo(Linguistics.SENTENCE_TYPE.STOP) == 0){
TODO

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			return Output.say("Now think of a character and tell me when you're ready to start the game.");
extend options and add in Verbalizer

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +				return Output.say("I have a problem finding a guess...");
more options to say it

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			return Output.say("Nice, then let's start");
add options

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			}
LOGGER.error entry 

add to all catch

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +		for(String token : tokens) {
should be a part of inference engine, not parsed here. 

there's also a switch operator more suitable for this case https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			return Output.say("I throw in the towel, I think I have no idea what to ask next. You win!");
logger.error

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			return Output.say("I throw in the towel, I think I have no idea what to ask next. You win!");
or info

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +	private Output saveUsersEstimate(String intent) throws Exception {
avoid adding throws Exception in function definition and handle them inside your function

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +					return Output.sayNothing();
in all of this cases we should probably say something to confirm roboy understood it correctly 
so change Output.sayNothing() to a reaction to the intent

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +	private Output doAGuess () throws Exception{
throw exception

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			winner = "interlocutor";
you can get the name of the interlocutor from context here directly

check other states for sample implementation

2018-06-13 13:19 UTC, missxa commented on src/main/java/roboy/dialog/states/ordinaryStates/GamingTwentyQuestionsState.java
> +			return Output.say("I won at my " + numberGuesses + ". guess.");
say something more fun here and let out the number of guesses

2018-06-23 20:29 UTC, missxa commented
@ninalovegood merge to devel again. make sure you keep config.properties from devel branch

2018-07-08 14:07 UTC, missxa requested changes

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/dialog/states/gameStates/GamingTwentyQuestionsState.java
> +		String intent = null;
so why this function can only return yes or no but in saveUsersEstimate() there're cases for all kinds?
how do intents like probably/maybe work?

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/dialog/states/gameStates/GamingTwentyQuestionsState.java
> +						return Output.say("Please answer with either YES, NO, DONT KNOW, PROBABLY or PROBABLY NOT or go back one question with BACK.");
this is not a way how we want roboy to talk. please rephrase in a more kind, funny and user-friendly way

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/dialog/states/gameStates/GamingTwentyQuestionsState.java
> +	private Output doAGuess (){
can we also do a guess in any case after 10 or 15 questions? it's getting to long imo

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/dialog/states/monologStates/ActiveIntroState.java
> +package roboy.dialog.states.monologStates;
please remove the new functionality from this PR, including this state, personality file, etc. it is only up to midterm

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/dialog/states/monologStates/IdleState.java
> +package roboy.dialog.states.monologStates;
not in this PR

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/logic/InferenceEngine.java
> +    List<String> inferSnapchatFilter(Interpretation input, Map<String,List<String>> existingFilterMap);
InferenceEngine is a very high level interface and shall not contain inferSnapchat or game methods. they should be local for Inference you are using or even located in corresponding states.

2018-07-08 14:07 UTC, missxa commented on dialog/src/main/java/roboy/util/SynonymFileParser.java
> +public class SynonymFileParser {
what is this for?

2018-07-08 14:07 UTC, missxa commented on docs/Project_Structure/4_Resources.rst
> +- synonym lists - contain keys and possible synonyms::
i dont think this is the way to go with synonyms. what do you use them for?

2018-07-08 14:07 UTC, missxa commented on resources/gameResources/snapchat-filters.json
> +{
ok, so i'm guessing these are the synonyms. they should live in the code and parsing it from file is even less nice than from code. if possible have them as final static variables inside corresponding states cause they're very use-case specific

2018-07-08 14:07 UTC, missxa commented on resources/gameResources/snapchat-filters.json
> +{
the roboy one is pretty generic, but the rest not so much

2018-07-08 14:07 UTC, missxa commented on resources/personalityFiles/AutomatedInteractionPesonality.json
> +{
not in this PR

2018-07-08 14:25 UTC, ninalovegood commented on dialog/src/main/java/roboy/logic/InferenceEngine.java
> +    List<String> inferSnapchatFilter(Interpretation input, Map<String,List<String>> existingFilterMap);
Eww okay... I am a bit confused because this is how you told me to do it the day we met and did the first merge... same with the parameters in resources/... for snapchat-filters

2018-07-08 14:31 UTC, missxa commented on config.properties
> +ROS_ENABLED: true
let's change it back to false

2018-07-08 14:31 UTC, missxa commented on config.properties
> +# PERSONALITY_FILE: "resources/personalityFiles/AutomatedInteractionPersonality.json"
not in this PR

2018-07-08 14:33 UTC, missxa commented on dialog/src/main/java/roboy/logic/InferenceEngine.java
> +    List<String> inferSnapchatFilter(Interpretation input, Map<String,List<String>> existingFilterMap);
regarding the snapchat names: I meant to store exact filter names how the python side is expecting it, not all possible synonyms, this is handle inside dialog.

2018-07-08 14:35 UTC, missxa commented on dialog/src/main/java/roboy/logic/InferenceEngine.java
> +    List<String> inferSnapchatFilter(Interpretation input, Map<String,List<String>> existingFilterMap);
regarding the inference, I meant meant having them inside Inference we are using, not the top level interface class InferenceEngine. now every time someone wants to implement their own Inference login they have to have your methods implemented which doesnt make sense

2018-07-10 12:43 UTC, ninalovegood commented on dialog/src/main/java/roboy/dialog/states/gameStates/GamingTwentyQuestionsState.java
> +	private Output doAGuess (){
I lowered the probability-threshold to 0.6, it came now with a guess after 10-13 questions!

2018-07-21 21:11 UTC, missxa approved these changes

2018-07-21 21:13 UTC, merged